name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [22.12.0]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd jin33-frontend
          npm ci

      - name: Type check
        run: |
          cd jin33-frontend
          npm run type-check

      - name: Lint
        run: |
          cd jin33-frontend
          npm run lint

      - name: Build
        run: |
          cd jin33-frontend
          npm run build
